### ISSUE TITLE
Typescript complains on utility-types

### ISSUE THREAD

**Issue by ivnnv** [Leo4815162342/dukascopy-node#107]
Hey, first of all, thanks for this great library 👍🏽 

Found out that Typescript complains on this devDep typing when running the app where `dukascopy-node` is used:

```
node_modules/dukascopy-node/dist/index.d.ts:1:30 - error TS2307: Cannot find module 'utility-types' or its corresponding type declarations.
1 import { OptionalKeys } from 'utility-types';
```

**Comment by Leo4815162342** [comment]
@ivnnv 
We've removed `utility-types`, please update to the version `1.30.1` and let us know if there are any other problems

**Comment by ivnnv** [comment]
Clean TS sheet now, thanks for the promp fix!

`[14:59:22] Found 0 errors. Watching for file changes.`
