### ISSUE TITLE
What unit is volume?

### ISSUE THREAD

**Issue by makovez** [Leo4815162342/dukascopy-node#120]
I don't understand why data coming from MT4 from dukascopy has not same volume unit of data downloaded from this library

**Comment by Leo4815162342** [comment]
@makovez 
the volume unit is in millions which corresponds to what Dukascopy  historical data feed  has here https://www.dukascopy.com/trading-tools/widgets/quotes/historical_data_feed

<img width="899" alt="Screenshot 2023-02-17 at 20 17 05" src="https://user-images.githubusercontent.com/12486774/219766562-9109b6ba-3645-475f-9f25-148204ca6d4e.png">

We can add an option to specify the unit type ('Unit', 'Thousands' or 'Millions') similar to how they have it

**Comment by makovez** [comment]
Is this dollar? I was looking at this https://www.dukascopy.com/swiss/it/marketwatch/charts/ and they seem to be completely different (not in scale).

For example for brentcmdusd m15 at 21:45 from your api 1675460700000,79.639,79.742,79.594,79.742,**0.0504**
And from dukascopy website...
![image](https://user-images.githubusercontent.com/21694707/219772858-41d64acb-5b2f-486a-9921-6ab5a2b78cac.png)

**Comment by makovez** [comment]
Thanks for your quick answer. Yes it would be nice to have this option.

**Comment by makovez** [comment]
Another question, Is the default timezone GMT/UTC ?

**Comment by Leo4815162342** [comment]
@makovez the date timestamps are in UTC

**Comment by makovez** [comment]
![image](https://user-images.githubusercontent.com/21694707/219942269-09ddff9b-8856-4417-b9ec-ba46222d7726.png)
Do you understand what does this mean then?

**Comment by Leo4815162342** [comment]
EET seems to  refer to Eastern European Time, but I don't see any effect of changing it either to EET or UTC in that widget 🤷

`dukascopy-node` returns data as unix timestamps in milliseconds, so you can use that output and convert them to any timezone you want.

**Comment by makovez** [comment]
Perfect! Thanks for your amazing library and your quick response's.
