### ISSUE TITLE
Please fix connection problems for downloading

### ISSUE THREAD

**Issue by walter2482** [Leo4815162342/dukascopy-node#124]
Along with greetings, I am currently having problems downloading files, I have tried many combinations of currency pairs, among others and always generates a disconnection.

I have tried reinstalling the modules and nodes, also in cloud computing with paperspace, but the connection always fails.

**Something went wrong:
 > {"message":"request to https://datafeed.dukascopy.com/datafeed/BTCUSD/2023/01/03/BID_candles_min_1.bi5 failed, reason: connect ETIMEDOUT 194.8.15.180:443","type":"system","errno":"ETIMEDOUT","code":"ETIMEDOUT"}**

![image](https://user-images.githubusercontent.com/93685420/221329894-d394d7ed-79cc-4c13-b662-c0ac6d65da28.png)

**Comment by Leo4815162342** [comment]
Recently the dukascopy datafeed servers have been quite unstable and sometimes don’t let some requests come through. Since we don’t have control over those servers, the only thing we can do from our side is to improve our retry logic after the server responds with error.

**Comment by walter2482** [comment]
Thank you very much for your response, your API is quite good, it allows
many options and volume in addition to the price unlike findatapy, I can
only wait for the servers to stabilize. I was able to download with
findatapy, but it is presenting the same connection errors, sometimes
downloading.

**Comment by Leo4815162342** [comment]
@walter2482 the new beta version with updated "retry" logic has been released.
```
npm install dukascopy-node@1.31.3-beta.4 --save
```

Also, for now please try using it in a low-batch mode - minimal of downloaded items per batch - it slows down the download a bit, but reduces load on the servers  - hence less errors:
```
npx dukascopy-node -i btcusd -from 2019-01-16 --batch-size 1 --retries 10 
```

**Comment by walter2482** [comment]
Thank you very much for stabilizing your API. I have tested more than 100 instruments about 40% some of them are incomplete especially the currency pairs, but it is much better since it is automated, I will just download again. I would like to reward you financially but I am just a student, I will remember your contribution when I get my salary.

**Comment by Leo4815162342** [comment]
@walter2482 thanks :)

Also to speed up consequent downloads for same (or overlapping by dates) downloads you can add `--cache` option to you CLI command. More info on cache: https://www.dukascopy-node.app/using-cache
