### ISSUE TITLE
Get all instruments list

### ISSUE THREAD

**Issue by stenioanibal** [Leo4815162342/dukascopy-node#132]
Any way to get the available instruments list?

**Comment by Leo4815162342** [comment]
@stenioanibal 
you can get the list programmatically via:

```typescript
import { Instrument } from "dukascopy-node";

const instrumentList = Object.keys(Instrument);
```

Reference to the respective enum: https://github.com/Leo4815162342/dukascopy-node/blob/master/src/utils/instrument-meta-data/generated/instrument-enum.ts

You can also view available instruments by category here: https://www.dukascopy-node.app/instruments
