### ISSUE TITLE
Promise.allSettled is not a function

### ISSUE THREAD

**Issue by MislavSag** [Leo4815162342/dukascopy-node#136]
When I run the command 

`npx dukascopy-node -i aaplususd -from 2019-01-13 -to 2019-01-14 -t tick -f csv -v true -ch true`

I got an error
Something went wrong:
 > Promise.allSettled is not a function

**Comment by Leo4815162342** [comment]
@MislavSag what version of node are you runnong? 
```
node -v
```
please make sure it's `12.9` or higher

**Comment by MislavSag** [comment]
Works after update. Sorry, I don't use node ussually.
