### ISSUE TITLE
Constant bid and ask volume when downloading tick data

### ISSUE THREAD

**Issue by MislavSag** [Leo4815162342/dukascopy-node#138]
If I set volume option to true when downloading tick data:
`npx dukascopy-node -i aaplususd -from 2023-04-09 --date-to now --timeframe tick --volumes true --format csv --cache true`

the resulted 'asVolume' and 'bidVolume' columns are constant for all rows and equa to 0.012.

Have I done something wrong or Dukacopy returns constant volumes?

**Comment by Leo4815162342** [comment]
@MislavSag there is definitely something that is not right. Can you check if you get the same via: https://www.dukascopy.com/trading-tools/widgets/quotes/historical_data_feed ?

**Comment by Leo4815162342** [comment]
seems like that how it is coming from the dukascopy servers, and `dukascopy-node` just aggregates whatever data is there
