### ISSUE TITLE
I can't install this fabulous package, here are the logs

### ISSUE THREAD

**Issue by sirokuma2023** [Leo4815162342/dukascopy-node#139]
0 verbose cli D:\Program Files\nodejs\node.exe D:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js
1 info using npm@9.5.0
2 info using node@v18.15.0
3 timing npm:load:whichnode Completed in 2ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:D:\Program Files\nodejs\node_modules\npm\npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:D:\vue\scratch\vite-project.npmrc Completed in 0ms
10 timing config:load:project Completed in 4ms
11 timing config:load:file:C:\Users\Administrator.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:C:\Users\Administrator\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 1ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 13ms
17 timing npm:load:configload Completed in 13ms
18 timing npm:load:mkdirpcache Completed in 0ms
19 timing npm:load:mkdirplogs Completed in 1ms
20 verbose title npm install dukascopy-node
21 verbose argv "install" "dukascopy-node" "--save"
22 timing npm:load:setTitle Completed in 1ms
23 timing config:load:flatten Completed in 4ms
24 timing npm:load:display Completed in 5ms
25 verbose logfile logs-max:10 dir:C:\Users\Administrator\AppData\Local\npm-cache_logs\2023-05-08T08_23_37_891Z-
26 verbose logfile C:\Users\Administrator\AppData\Local\npm-cache_logs\2023-05-08T08_23_37_891Z-debug-0.log
27 timing npm:load:logFile Completed in 10ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 32ms
31 timing arborist:ctor Completed in 1ms
32 silly logfile start cleaning logs, removing 2 files
33 timing arborist:ctor Completed in 0ms
34 silly logfile done cleaning log files
35 timing idealTree:init Completed in 926ms
36 timing idealTree:userRequests Completed in 4ms
37 silly idealTree buildDeps
38 silly fetch manifest dukascopy-node@*
39 http fetch GET 200 https://registry.npmjs.org/dukascopy-node 1679ms (cache revalidated)
40 silly placeDep ROOT dukascopy-node@1.34.0 OK for: vite-project@0.0.0 want: *
41 silly fetch manifest chalk@3.0.0
42 silly fetch manifest cli-progress@3.10.0
43 silly fetch manifest commander@5.0.0
44 silly fetch manifest debug@4.3.4
45 silly fetch manifest fastest-validator@1.10.0
46 silly fetch manifest fs-extra@10.1.0
47 silly fetch manifest lzma-purejs@git+https://github.com/Leo4815162342/lzma-purejs.git
48 silly fetch manifest node-fetch@2.6.7
49 silly fetch manifest python-struct@1.1.3
50 http fetch GET 200 https://registry.npmjs.org/debug 387ms (cache revalidated)
51 http fetch GET 200 https://registry.npmjs.org/cli-progress 976ms (cache revalidated)
52 http fetch GET 200 https://registry.npmjs.org/chalk 985ms (cache revalidated)
53 http fetch GET 200 https://registry.npmjs.org/fs-extra 998ms (cache revalidated)
54 http fetch GET 200 https://registry.npmjs.org/node-fetch 1000ms (cache revalidated)
55 http fetch GET 200 https://registry.npmjs.org/commander 1008ms (cache revalidated)
56 http fetch GET 200 https://registry.npmjs.org/fastest-validator 1355ms (cache revalidated)
57 http fetch GET 200 https://registry.npmjs.org/python-struct 2217ms (cache revalidated)
58 timing idealTree:#root Completed in 3922ms
59 silly fetch manifest encoding@^0.1.0
60 http fetch GET 200 https://registry.npmjs.org/encoding 342ms (cache revalidated)
61 silly placeDep ROOT chalk@3.0.0 OK for: dukascopy-node@1.34.0 want: 3.0.0
62 silly placeDep ROOT cli-progress@3.10.0 OK for: dukascopy-node@1.34.0 want: 3.10.0
63 silly placeDep ROOT commander@5.0.0 OK for: dukascopy-node@1.34.0 want: 5.0.0
64 silly placeDep ROOT debug@4.3.4 OK for: dukascopy-node@1.34.0 want: 4.3.4
65 timing idealTree Completed in 5224ms
66 timing command:install Completed in 5233ms
67 verbose stack TypeError: Cannot read properties of null (reading 'matches')
67 verbose stack at Link.matches (D:\Program Files\nodejs\node_modules\npm\node_modules@npmcli\arborist\lib\node.js:1119:41)
67 verbose stack at Link.canDedupe (D:\Program Files\nodejs\node_modules\npm\node_modules@npmcli\arborist\lib\node.js:1073:15)
67 verbose stack at PlaceDep.pruneDedupable (D:\Program Files\nodejs\node_modules\npm\node_modules@npmcli\arborist\lib\place-dep.js:426:14)
67 verbose stack at new PlaceDep (D:\Program Files\nodejs\node_modules\npm\node_modules@npmcli\arborist\lib\place-dep.js:278:14)
67 verbose stack at D:\Program Files\nodejs\node_modules\npm\node_modules@npmcli\arborist\lib\arborist\build-ideal-tree.js:943:31
67 verbose stack at Array.map ()
67 verbose stack at [buildDepStep] (D:\Program Files\nodejs\node_modules\npm\node_modules@npmcli\arborist\lib\arborist\build-ideal-tree.js:943:8)
67 verbose stack at async Arborist.buildIdealTree (D:\Program Files\nodejs\node_modules\npm\node_modules@npmcli\arborist\lib\arborist\build-ideal-tree.js:207:7)
67 verbose stack at async Promise.all (index 1)
67 verbose stack at async Arborist.reify (D:\Program Files\nodejs\node_modules\npm\node_modules@npmcli\arborist\lib\arborist\reify.js:159:5)
68 verbose cwd D:\vue\scratch\vite-project
69 verbose Windows_NT 10.0.19044
70 verbose node v18.15.0
71 verbose npm v9.5.0
72 error Cannot read properties of null (reading 'matches')
73 verbose exit 1
74 timing npm Completed in 5297ms
75 verbose unfinished npm timer reify 1683534217951
76 verbose unfinished npm timer reify:loadTrees 1683534217954
77 verbose unfinished npm timer idealTree:buildDeps 1683534218885
78 verbose unfinished npm timer idealTree:node_modules/dukascopy-node 1683534222808
79 verbose code 1
80 error A complete log of this run can be found in:
80 error C:\Users\Administrator\AppData\Local\npm-cache_logs\2023-05-08T08_23_37_891Z-debug-0.log

**Comment by Leo4815162342** [comment]
@sirokuma2023 
what exact command did you run?

**Comment by sirokuma2023** [comment]
> @sirokuma2023 what exact command did you run?

The logs are from npm install dukascopy-node --save, I also tried the others, but didn't work.

**Comment by Leo4815162342** [comment]
@sirokuma2023 what node version do you have?
```
node -v
```

**Comment by sirokuma2023** [comment]
> 

"node": "^19.8.1",

**Comment by sirokuma2023** [comment]
> @sirokuma2023 what node version do you have?
> 
> ```
> node -v
> ```

"node": "^19.8.1",

**Comment by Leo4815162342** [comment]
@sirokuma2023 just tried `19.8.1` and all worked, at least on mac.
Can you try installing node 16 and 18 to check if the issue still persists on your side?

**Comment by sirokuma2023** [comment]
> @sirokuma2023 just tried `19.8.1` and all worked, at least on mac. Can you try installing node 16 and 18 to check if the issue still persists on your side?

Thank you for keeping in mind. Another node version works. Your project is really amazing.
