### ISSUE TITLE
tick data is not tick data

### ISSUE THREAD

**Issue by arainboldt** [Leo4815162342/dukascopy-node#142]
this is what is downloaded when using `-t tick`. this isn't tick data:

![image](https://github.com/Leo4815162342/dukascopy-node/assets/54881218/638b82e9-f9f1-4ef2-88d6-30a8b5e3b423)

**Comment by Leo4815162342** [comment]
@arainboldt could you please elaborate?

**Comment by arainboldt** [comment]
the above isn't tick data. these are bids/asks. tick data is the records of each executed transaction with:

1. time of transaction
2. price
3. volume

**Comment by Leo4815162342** [comment]
@arainboldt 
the output for  `-t tick `downloads contains timestamp, price (both bid/ask) and respective volume.

You can compare the output with the native historical data feed downloader here: https://www.dukascopy.com/trading-tools/widgets/quotes/historical_data_feed

**Comment by arainboldt** [comment]
@Leo4815162342 thanks for sharing the link. I don't have a n account at dukascopy, so I can't download. but the point is that just bid/ask prices don't tell you what transactions have actually occurred. Interestingly, when you select tick as the frequency, the bid/ask options are disabled. this indicates that it's implied that bid/ask will be provided or excluded. perhaps the Swiss use a different definition of tick than is used in the US.  can't say. In any case, afaik tick data refers to records of actual individual transactions, not bids/asks.

![image](https://github.com/Leo4815162342/dukascopy-node/assets/54881218/7c71a9a6-05ab-455c-b8e5-b06b2a92c28f)

**Comment by Leo4815162342** [comment]
@arainboldt I see, thank you for clarification. In this case in the context of dukascopy, tick data is indeed not a record of individual transactions
