### ISSUE TITLE
instruments list

### ISSUE THREAD

**Issue by dawadam** [Leo4815162342/dukascopy-node#143]
Hi,
thank you for this great work.

Is there a list of instruments?
Other than in the README?

I would like to generate an HTML selector with category.

**Comment by Leo4815162342** [comment]
@dawadam the full list of instruments and their meta data is available here: https://github.com/Leo4815162342/dukascopy-node/blob/master/src/utils/instrument-meta-data/generated/instrument-meta-data.json
