### ISSUE TITLE
[type] getHistoricalRates result can be a string

### ISSUE THREAD

**Issue by dawadam** [Leo4815162342/dukascopy-node#153]
When using format "csv", result of getHistoricalRates methode is string, but result type not.

**Comment by Leo4815162342** [comment]
@dawadam what version of package are you using? can you share the exact script you're running?

**Comment by Leo4815162342** [comment]
@dawadam there is an expoerted csv-based config: `CurrentRatesConfigCsv`

```typescript
import { CurrentRatesConfigCsv } from 'dukascopy-node';
```


if you are on one of the latest version of typescript (4.9+) you can use 'satisfies' keyword that preserves "narrowness" of the input config and allows for proper inference of the output type:

```typescript
  const since = 1690848000000;
  const h24 = 60 * 1000 * 60 * 24 * 5;
  //
  const testConfigRequest = {
    instrument: 'eurusd',
    dates: {
      from: since,
      to: since + h24,
    },
    timeframe: 'm1',
    format: 'csv',
  } satisfies Config;
  const test = await getHistoricalRates(testConfigRequest)
      //^ const test: string
```


<img width="522" alt="Screenshot 2023-08-14 at 15 09 30" src="https://github.com/Leo4815162342/dukascopy-node/assets/12486774/fdbfcd94-1f49-4011-973f-825812df6fbf">
