### ISSUE TITLE
[feature] Custom output file name

### ISSUE THREAD

**Issue by groschovskiy** [Leo4815162342/dukascopy-node#155]
Would be great to add custom output file name. For example if I want to save a file as EURUSD-M1.csv

**Comment by Leo4815162342** [comment]
the new version has been released `1.36.1`

you can now modify the file name via `--file-name` param:

```bash
npx dukascopy-node -i eurusd -from 2019-01-13 -to 2019-01-16 -t m1 -f csv --file-name EURUSD-M1
```
