### ISSUE TITLE
Unable to verify the first certificate error

### ISSUE THREAD

**Issue by pagkly** [Leo4815162342/dukascopy-node#164]
Hi, would like to ask if there is any solution for this error happening to both my PCs:

PS C:\Users\user> npx dukascopy-node -i audsgd -from 2023-11-19 -to 2023-11-20 -t tick -f csv -v -vu units
----------------------------------------------------
Downloading historical price data for:
----------------------------------------------------
Instrument:     Australian Dollar vs Singapore Dollar
Timeframe:      tick
From date:      Nov 19, 2023, 12:00:00 AM
To date:        Nov 20, 2023, 12:00:00 AM
Volumes:        true
UTC Offset:     0
Include flats:  false
Format:         csv
----------------------------------------------------
|░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░| 0%(node:25724) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alt.
(Use `node --trace-deprecation ...` to show where the warning was created)

Something went wrong:
request to https://datafeed.dukascopy.com/datafeed/AUDSGD/2023/10/19/06h_ticks.bi5 failed, reason: unable to verify the first certificate

However, I can download the file when opening in browser

**Comment by Leo4815162342** [comment]
@pagkly sorry for a delayed response. That seems to have been an issue with the dukascopy server. Let me know if you are still experiencing the issue
