### ISSUE TITLE
Downloading all the data and keeping in sync

### ISSUE THREAD

**Issue by jmakov** [Leo4815162342/dukascopy-node#175]
Is there a way to download all the data with one command and keeping it in sync e.g. you download everything on 2024-01-10 and run again the command on 2024-02-10 to get only the deltas, kinda like rsync?

**Comment by Leo4815162342** [comment]
@jmakov if you want to achieve similar thing, you can try using the CLI with cache https://www.dukascopy-node.app/using-cache it will cache underlying artifacts on disc, and upon next execution will not reach out to the network.

Docs on how to enable caching: https://www.dukascopy-node.app/using-cache
