### ISSUE TITLE
LNK/USD data is wrong.

### ISSUE THREAD

**Issue by straitsboy** [Leo4815162342/dukascopy-node#178]
Chainlink is trading today at $14+. The dukascopy-node downloads says it's $147+. 
I wonder why...

The chart at dukascopy website is correct though...

**Comment by straitsboy** [comment]
BAT/USD is wrong too.. by a factor of about 100.
LNK/USD is off by a factor of 10.

**Comment by straitsboy** [comment]
UNI/USD (Uniswap) is also off by a factor of 10.
All other cryptos look ok.

**Comment by Leo4815162342** [comment]
Thanks for reporting this @straitsboy 🙏🏻
This will be fixed in the next release

**Comment by Leo4815162342** [comment]
@straitsboy the issue has been fixed and is available in the version `1.39.2` and above

**Comment by straitsboy** [comment]
Wonderful! Thank you! Closing this...
