### ISSUE TITLE
BUG: generating wrong file name due to time calculation error.

### ISSUE THREAD

**Issue by WeskerC** [Leo4815162342/dukascopy-node#183]
Hello Leo, I have found a bug in the tool. @Leo4815162342

When input datetime    2024-06-21, the month will be -1 when generating file names for downloading.

Please solve this bug. 

(I think it is the reason why I get 0KB file(it says 1.68MB but actually 0) even though I have downloaded 24 bi5 files which are not empty files but failed to compose together in the end.)

![image](https://github.com/Leo4815162342/dukascopy-node/assets/48875935/230bb056-28aa-4b30-a37e-23a74ecb6513)

PS G:\> npx dukascopy-node -i gbpusd -from 2024-06-21 -to 2024-06-22 -t tick -d --retry-on-empty 10 -f csv
  dukascopy-node:cli:version 1.39.0 +0ms
  dukascopy-node:cli:nodejs v20.14.0 +0ms
  dukascopy-node:cli:os Windows_NT, 10.0.22621 (win32) +0ms
  dukascopy-node:cli:config {
  dukascopy-node:cli:config   input: {
  dukascopy-node:cli:config     instrument: 'gbpusd',
  dukascopy-node:cli:config     dates: { from: 2024-06-21T00:00:00.000Z, to: 2024-06-22T00:00:00.000Z },
  dukascopy-node:cli:config     timeframe: 'tick',
  dukascopy-node:cli:config     priceType: 'bid',
  dukascopy-node:cli:config     utcOffset: 0,
  dukascopy-node:cli:config     volumes: false,
  dukascopy-node:cli:config     volumeUnits: 'millions',
  dukascopy-node:cli:config     ignoreFlats: true,
  dukascopy-node:cli:config     dir: './download',
  dukascopy-node:cli:config     silent: false,
  dukascopy-node:cli:config     format: 'csv',
  dukascopy-node:cli:config     batchSize: 10,
  dukascopy-node:cli:config     pauseBetweenBatchesMs: 1000,
  dukascopy-node:cli:config     useCache: false,
  dukascopy-node:cli:config     cacheFolderPath: './.dukascopy-cache',
  dukascopy-node:cli:config     retryCount: 0,
  dukascopy-node:cli:config     failAfterRetryCount: true,
  dukascopy-node:cli:config     retryOnEmpty: true,
  dukascopy-node:cli:config     pauseBetweenRetriesMs: 500,
  dukascopy-node:cli:config     debug: true,
  dukascopy-node:cli:config     inline: false,
  dukascopy-node:cli:config     fileName: '',
  dukascopy-node:cli:config     dateFormat: '',
  dukascopy-node:cli:config     timeZone: ''
  dukascopy-node:cli:config   },
  dukascopy-node:cli:config   isValid: true,
  dukascopy-node:cli:config   validationErrors: []
  dukascopy-node:cli:config } +0ms
  dukascopy-node:cli:urls Generated 20 urls +0ms
  dukascopy-node:cli:urls [
  dukascopy-node:cli:urls   'https://datafeed.dukascopy.com/datafeed/GBPUSD/2024/05/21/00h_ticks.bi5',
  dukascopy-node:cli:urls   'https://datafeed.dukascopy.com/datafeed/GBPUSD/2024/05/21/01h_ticks.bi5',
  dukascopy-node:cli:urls   'https://datafeed.dukascopy.com/datafeed/GBPUSD/2024/05/21/02h_ticks.bi5',
  dukascopy-node:cli:urls   'https://datafeed.dukascopy.com/datafeed/GBPUSD/2024/05/21/03h_ticks.bi5',
  dukascopy-node:cli:urls   'https://datafeed.dukascopy.com/datafeed/GBPUSD/2024/05/21/04h_ticks.bi5',
  dukascopy-node:cli:urls   'https://datafeed.dukascopy.com/datafeed/GBPUSD/2024/05/21/05h_ticks.bi5',
  dukascopy-node:cli:urls   'https://datafeed.dukascopy.com/datafeed/GBPUSD/2024/05/21/06h_ticks.bi5',
  dukascopy-node:cli:urls   'https://datafeed.dukascopy.com/datafeed/GBPUSD/2024/05/21/07h_ticks.bi5',
  dukascopy-node:cli:urls   'https://datafeed.dukascopy.com/datafeed/GBPUSD/2024/05/21/08h_ticks.bi5',
  dukascopy-node:cli:urls   'https://datafeed.dukascopy.com/datafeed/GBPUSD/2024/05/21/09h_ticks.bi5',
  dukascopy-node:cli:urls   'https://datafeed.dukascopy.com/datafeed/GBPUSD/2024/05/21/10h_ticks.bi5',
  dukascopy-node:cli:urls   'https://datafeed.dukascopy.com/datafeed/GBPUSD/2024/05/21/11h_ticks.bi5',
  dukascopy-node:cli:urls   'https://datafeed.dukascopy.com/datafeed/GBPUSD/2024/05/21/12h_ticks.bi5',
  dukascopy-node:cli:urls   'https://datafeed.dukascopy.com/datafeed/GBPUSD/2024/05/21/13h_ticks.bi5',
  dukascopy-node:cli:urls   'https://datafeed.dukascopy.com/datafeed/GBPUSD/2024/05/21/14h_ticks.bi5',
  dukascopy-node:cli:urls   'https://datafeed.dukascopy.com/datafeed/GBPUSD/2024/05/21/15h_ticks.bi5',
  dukascopy-node:cli:urls   'https://datafeed.dukascopy.com/datafeed/GBPUSD/2024/05/21/16h_ticks.bi5',
  dukascopy-node:cli:urls   'https://datafeed.dukascopy.com/datafeed/GBPUSD/2024/05/21/17h_ticks.bi5',
  dukascopy-node:cli:urls   'https://datafeed.dukascopy.com/datafeed/GBPUSD/2024/05/21/18h_ticks.bi5',
  dukascopy-node:cli:urls   'https://datafeed.dukascopy.com/datafeed/GBPUSD/2024/05/21/19h_ticks.bi5'
  dukascopy-node:cli:urls ] +0ms
  dukascopy-node:cli:fetcher https://datafeed.dukascopy.com/datafeed/GBPUSD/2024/05/21/00h_ticks.bi5 | 7.11 KB | network +0ms
  dukascopy-node:cli:fetcher https://datafeed.dukascopy.com/datafeed/GBPUSD/2024/05/21/09h_ticks.bi5 | 11.88 KB | network +0ms
  dukascopy-node:cli:fetcher https://datafeed.dukascopy.com/datafeed/GBPUSD/2024/05/21/08h_ticks.bi5 | 18.73 KB | network +0ms
  dukascopy-node:cli:fetcher https://datafeed.dukascopy.com/datafeed/GBPUSD/2024/05/21/07h_ticks.bi5 | 22.49 KB | network +0ms
  dukascopy-node:cli:fetcher https://datafeed.dukascopy.com/datafeed/GBPUSD/2024/05/21/02h_ticks.bi5 | 6.74 KB | network +0ms
  dukascopy-node:cli:fetcher https://datafeed.dukascopy.com/datafeed/GBPUSD/2024/05/21/03h_ticks.bi5 | 4.01 KB | network +0ms
  dukascopy-node:cli:fetcher https://datafeed.dukascopy.com/datafeed/GBPUSD/2024/05/21/04h_ticks.bi5 | 3.59 KB | network +0ms
  dukascopy-node:cli:fetcher https://datafeed.dukascopy.com/datafeed/GBPUSD/2024/05/21/05h_ticks.bi5 | 4.34 KB | network +0ms
  dukascopy-node:cli:fetcher https://datafeed.dukascopy.com/datafeed/GBPUSD/2024/05/21/01h_ticks.bi5 | 10.2 KB | network +0ms
  dukascopy-node:cli:fetcher https://datafeed.dukascopy.com/datafeed/GBPUSD/2024/05/21/06h_ticks.bi5 | 17.3 KB | network +0ms
  dukascopy-node:cli:fetcher https://datafeed.dukascopy.com/datafeed/GBPUSD/2024/05/21/17h_ticks.bi5 | 8.7 KB | network +0ms
  dukascopy-node:cli:fetcher https://datafeed.dukascopy.com/datafeed/GBPUSD/2024/05/21/10h_ticks.bi5 | 12.51 KB | network +0ms
  dukascopy-node:cli:fetcher https://datafeed.dukascopy.com/datafeed/GBPUSD/2024/05/21/18h_ticks.bi5 | 8.05 KB | network +0ms
  dukascopy-node:cli:fetcher https://datafeed.dukascopy.com/datafeed/GBPUSD/2024/05/21/15h_ticks.bi5 | 16.25 KB | network +0ms
  dukascopy-node:cli:fetcher https://datafeed.dukascopy.com/datafeed/GBPUSD/2024/05/21/12h_ticks.bi5 | 15.28 KB | network +0ms
  dukascopy-node:cli:fetcher https://datafeed.dukascopy.com/datafeed/GBPUSD/2024/05/21/14h_ticks.bi5 | 28.82 KB | network +0ms
  dukascopy-node:cli:fetcher https://datafeed.dukascopy.com/datafeed/GBPUSD/2024/05/21/19h_ticks.bi5 | 7.36 KB | network +0ms
  dukascopy-node:cli:fetcher https://datafeed.dukascopy.com/datafeed/GBPUSD/2024/05/21/13h_ticks.bi5 | 23.78 KB | network +0ms
  dukascopy-node:cli:fetcher https://datafeed.dukascopy.com/datafeed/GBPUSD/2024/05/21/11h_ticks.bi5 | 13.4 KB | network +0ms
  dukascopy-node:cli:fetcher https://datafeed.dukascopy.com/datafeed/GBPUSD/2024/05/21/16h_ticks.bi5 | 14.48 KB | network +0ms
----------------------------------------------------
√ File saved: download\gbpusd-tick-2024-06-21-2024-06-21T20:38.csv (1.68 MB)

Download time: 7.8s

**Comment by Leo4815162342** [comment]
@WeskerC
This is intentional. Dukascopy stores months starting from 0: (00 - January, 01 - February, 11 - December)
