### ISSUE TITLE
ENOTFOUND Error

### ISSUE THREAD

**Issue by denizbilgin** [Leo4815162342/dukascopy-node#191]
I'm trying to run this code:
`npx dukascopy-node -i btcusd -from 2019-01-13 -to 2019-01-14 -t tick -f json -d`

And the output is like that:
![image](https://github.com/user-attachments/assets/6962c138-2f8e-4802-b4af-24973a1c3705)

Also the error message is like that:
`Something went wrong:
 > {"message":"request to https://datafeed.dukascopy.com/datafeed/BTCUSD/2019/00/13/00h_ticks.bi5 failed, reason: getaddrinfo ENOTFOUND datafeed.dukascopy.com","type":"system","errno":"ENOTFOUND","code":"ENOTFOUND"}`
 
 I entered the date from 2019-01-13 to 2019-01-14. But as you can see in the image, it is looking for a date like 2019-00-13. I got the error because there was no month 00 and there was no link to it.

**Comment by denizbilgin** [comment]
Also when I try that with a different code like that:
`npx dukascopy-node -i antogbgbx -from 2024-03-19 -to 2024-03-20 -t m1 -f csv -d`

I got this kind of output:
![image](https://github.com/user-attachments/assets/8751edbf-b739-4757-a847-cd79c9e172b1)
Now I entered a period from 2024-03-19 to 2024-03-20 but it is looking for 2024-02-19

**Comment by Leo4815162342** [comment]
@denizbilgin 

does opening https://datafeed.dukascopy.com/datafeed/BTCUSD/2019/00/13/00h_ticks.bi5  link work?

in some cases dukascopy seems to block some URLs from certain IPs, or rate limits them.

As for the requested date range (2024-03-19 to 2024-03-20), the "to" date is always excluded.

**Comment by denizbilgin** [comment]
No, the site in the link you mentioned cannot be reached. I think the problem is not that the day written with "to" is not included. While I am requesting the data for the 3rd month, it tells me that it cannot access the data for the 2nd month.

**Comment by denizbilgin** [comment]
I tried to download using VPN services and it worked. As you said, probably some IP addresses from certain countries are blocked.
