### ISSUE TITLE
Dukascopy-cli: download more than one instrument

### ISSUE THREAD

**Issue by lezwright** [Leo4815162342/dukascopy-node#20]
One more question, is it possible to download more than one instrument at the time?

**Comment by tiaringhio** [comment]
I don't know if you still need the answer but put `npx` before your command. Example:

`npx dukascopy-cli -i gbridxgbp -from 2019-01-01 -to 2021-01-01 -t m1 -fl true -f csv`

Hope thath helps!

**Comment by lezwright** [comment]
thanks @tiaringhio . I still needed it :-)  

Also, @Leo4815162342 , some of the currency pairs cannot be downloaded in general, more specifically they are: EURTRY, EURHUF and USDTRY. Do you possibly know where the problem is?

**Comment by lezwright** [comment]
Hi @Leo4815162342 ,

Here is the screenshot of the error I get for EURDKK
![image](https://user-images.githubusercontent.com/61321682/111209043-6ab07c00-85c3-11eb-80f9-45f103e483a2.png)

**Comment by Leo4815162342** [comment]
@lezwright thanks for the screenshot. What are the values for the timeframe and the date range?
Can you try updating `dukascopy-node` to version `1.5.0`? - we've added few safe checks there to fix such errors

**Comment by lezwright** [comment]
Hi @Leo4815162342 ,

I narrowed down the problem, they cannot be loaded on 15 min, or 1 hour timeframes. I can only load them on 1 minutes timeframes. 

By the way, I have updated the library. Still same results. 

Thanks
