### ISSUE TITLE
Be able to get the latest data without specifying a specific date

### ISSUE THREAD

**Issue by 80586** [Leo4815162342/dukascopy-node#76]
Thanks for this handy project and the docs on Github.

Today's date: 2022-05-25

Without a way to indicate you want the latest data, as a workaround we use tomorrow's date.
This workaround does not work on all instruments.

Proposed solution:
 - Be able to specify "now" as an argument for "to" and let the application decide. iirc JS has a built-in Date.now() function

The difference between the two instruments may be because brentcmdusd has a little more data than ausidxaud. This may be a related bug.

 ❌ npx dukascopy-cli -from 2022-05-20 -to 2022-05-26 -t h1 -f json -i ausidxaud --volumes (Cannot read properties of undefined (reading '0'))
 ✅ npx dukascopy-cli -from 2022-05-20 -to 2022-05-26 -t h1 -f json -i brentcmdusd --volumes
 
Version: 1.19.2

**Comment by Leo4815162342** [comment]
@80586 thanks for the suggestion,  that's a really good idea, this should not be hard to implement.

As for the bug, I'll will investigate it, and will report back

**Comment by Leo4815162342** [comment]
@80586 the issue with `ausidxaud` not being able to download has been identified and fixed. Please upgrade `dukascopy-node` to `1.19.3` 

as for the `now` as `date to` value,  we'll work with @lazeratops to properly enable that

**Comment by 80586** [comment]
Thank you for this wonderful project. Better than most "enterprise" tools.

 ✅ can be used as CLI or as a library
 ✅ documentation
 ✅ short release cycle
 ✅ wiki
 ✅ semantic versioning
 ✅ tests
 ✅ free of charge

**Comment by Leo4815162342** [comment]
@80586 thank you for the feedback ❤️.
And there is even more cool feature to come in the future. So keep an eye on the releases :)
