### ISSUE TITLE
Incorrect initial date

### ISSUE THREAD

**Issue by cTatu** [Leo4815162342/dukascopy-node#87]
The saved file has the original starting date instead of the one given by the server.
The file should be download/gascmdusd-m1-bid-**2012-09-02**-2022-08-17.csv

![image](https://user-images.githubusercontent.com/37102803/185451931-822d09a4-89b9-4beb-81d0-ad545e9d17b5.png)

**Comment by Leo4815162342** [comment]
@cTatu good catch, will release a fix soon

**Comment by Leo4815162342** [comment]
@cTatu here is the new release `1.22.2` that fixes that: https://github.com/Leo4815162342/dukascopy-node/releases/tag/v1.22.2 - please update
